// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var React = {};

var Handlers = {};

var Classes = {};

exports.React = React;
exports.Handlers = Handlers;
exports.Classes = Classes;
/* No side effect */
